version: 2

project_name: idor-scan

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

brews:
  - repository:
      owner: itxdeeni
      name: homebrew-tap
    homepage: https://github.com/itxdeeni/idor-scan
    description: Automated IDOR & Access Control Testing for REST APIs
    license: MIT

nfpms:
  - package_name: idor-scan
    homepage: https://github.com/itxdeeni/idor-scan
    description: Automated IDOR & Access Control Testing for REST APIs
    maintainer: itxdeeni <zahradeenmuazu@yahoo.com>
    license: MIT
    formats:
      - deb
      - rpm
